#!/usr/bin/env python

import psutil
import usb
import sys

from blinkstick import blinkstick
from random import *
from time import *

bstick_left = blinkstick.find_by_serial('BS000537-1.1')
bstick_right = blinkstick.find_by_serial('BS000561-1.1')

c1 = [255,0,0]
c2 = [0,254,0]

while True:
    try:
        bstick_left.set_color(c1[0],c1[1],c1[2])
        bstick_right.set_color(c2[0],c2[1],c2[2])
        sleep(0.5)
        bstick_left.set_color(c2[0],c2[1],c2[2])
        bstick_right.set_color(c1[0],c1[1],c1[2])
        sleep(0.5)

    except usb.core.USBError:
        pass

    except KeyboardInterrupt:
        bstick_left.set_color(0,0,0)
        bstick_right.set_color(0,0,0)
        sys.exit(0)
